[project]
name = "denis-automation-for-qapractice"
version = "0.1.0"
description = "Student Playwright + Pytest framework for https://www.qapractice.com/"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "allure-pytest>=2.16.2",
    "faker>=40.40.0",
    "pytest>=8.3.0",
    "pytest-playwright>=0.6.2",
    "python-dotenv>=1.2.4",
]
